const stellplaetze = [
  {
    id: 1,
    name: "Parkplatz Seeufer Thun",
    lat: 46.7520,
    lng: 7.6280,
    typ: ["wohnmobil", "kastenwagen", "auto_dachzelt"],
    uebernachtung: ["wildcampen", "stellplatz"],
    maxLaenge: 8,
    maxHoehe: 4,
    beschreibung: "Ruhiger Parkplatz direkt am Thunersee. Nachts kostenlos.",
    land: "CH",
  },
  {
    id: 2,
    name: "Rastplatz Gotthard A2",
    lat: 46.5930,
    lng: 8.5640,
    typ: ["wohnmobil", "kastenwagen", "auto_dachzelt"],
    uebernachtung: ["rastplatz"],
    maxLaenge: 12,
    maxHoehe: 4,
    beschreibung: "Offizieller Rastplatz an der A2. Übernachtung erlaubt.",
    land: "CH",
  },
  {
    id: 3,
    name: "Stellplatz Lugano Sud",
    lat: 45.9850,
    lng: 8.9440,
    typ: ["wohnmobil", "kastenwagen"],
    uebernachtung: ["stellplatz"],
    maxLaenge: 9,
    maxHoehe: 3.5,
    beschreibung: "Offizieller Wohnmobilstellplatz mit Strom und Wasser.",
    land: "CH",
  },
  {
    id: 4,
    name: "Wanderparkplatz Grindelwald",
    lat: 46.6240,
    lng: 8.0410,
    typ: ["auto_dachzelt", "wohnmobil"],
    uebernachtung: ["wildcampen", "stellplatz"],
    maxLaenge: 7,
    maxHoehe: 3,
    beschreibung: "Ausgangspunkt für Wanderungen. Übernachtung geduldet.",
    land: "CH",
  },
  {
    id: 5,
    name: "Biwakplatz Sustenpass",
    lat: 46.7340,
    lng: 8.4450,
    typ: ["wanderer", "zelt", "backpacker"],
    uebernachtung: ["wildcampen"],
    beschreibung: "Freier Biwakplatz auf 2224m. Nur zu Fuss erreichbar.",
    land: "CH",
  },
  {
    id: 6,
    name: "Camping Tenero",
    lat: 46.1720,
    lng: 8.8520,
    typ: ["wohnmobil", "kastenwagen", "auto_dachzelt", "zelt", "backpacker"],
    uebernachtung: ["camping"],
    maxLaenge: 12,
    maxHoehe: 4,
    beschreibung: "Grosser Campingplatz am Lago Maggiore. Alle Einrichtungen vorhanden.",
    land: "CH",
  },
  {
    id: 7,
    name: "Freier Stellplatz Verzasca",
    lat: 46.2580,
    lng: 8.8320,
    typ: ["wohnmobil", "kastenwagen", "auto_dachzelt"],
    uebernachtung: ["wildcampen"],
    maxLaenge: 7,
    maxHoehe: 3,
    beschreibung: "Wildromantisch am Fluss. Kostenlos, keine Infrastruktur.",
    land: "CH",
  },
  {
    id: 8,
    name: "Schutzhütte Wildhorn",
    lat: 46.3520,
    lng: 7.4180,
    typ: ["wanderer", "backpacker"],
    uebernachtung: ["huette"],
    beschreibung: "SAC Hütte auf 2303m. Reservation empfohlen.",
    land: "CH",
  },
];

export default stellplaetze;